# For more information on configuration, see:
#   * Official English Documentation: http://nginx.org/en/docs/
#   * Official Russian Documentation: http://nginx.org/ru/docs/

user nginx;
worker_processes auto;
error_log /var/log/nginx/error.log;
pid /run/nginx.pid;

# Load dynamic modules. See /usr/share/nginx/README.dynamic.
include /usr/share/nginx/modules/*.conf;

events {
    worker_connections 1024;
}

http {


   map $http_referer $proxy_host {
	  ~/mypage			     "$backend1";
          ~/toiawase/keiyakusya              "$backend2";
          ~/update_contract                  "$backend2";
          ~/cancellation                     "$backend2";
          ~/payment-method-change-list       "$backend2";
          ~/customer_info_change_request     "$backend2";
          ~/customer-info-change-list        "$backend2";
          ~/issue-paper-parcel-list          "$backend2";
          ~/pre_cancellation                 "$backend2";
          ~/mf_realty                        "$backend2";
  	  ~/toiawase/cancel-contract-contact "$backend1";
          ~/cancel-contract                  "$backend2";
          ~/payment_method_change_request    "$backend2";
          ~/toiawase/switch-contract         "$backend1";
          ~/switch-contract                  "$backend2";
          ~/my-page-form                     "$backend2";
          ~/styles.+                         "$backend2";
          ~/assets                           "$backend2";
          ~/business_info                    "$backend2";
          ~/no-page                          "$backend2";
          ~/campaign                         "$backend2";
          default                            "$backend1";
    }


    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile            on;
    tcp_nopush          on;
    tcp_nodelay         on;
    keepalive_timeout   65;
    types_hash_max_size 2048;

    include             /etc/nginx/mime.types;
    default_type        application/octet-stream;

    geo $office_ip_addr {
        default         1;
        }

    server {
	location /health/ {
	    return 200 "OK";
	
    }


    # Load modular configuration files from the /etc/nginx/conf.d directory.
    # See http://nginx.org/en/docs/ngx_core_module.html#include
    # for more information.
    include /etc/nginx/conf.d/*.conf;

}
