name: 'set variables for each environments'
description: |
  '環境毎の変数を追加したい場合、このアクションで定義してください。'

runs:
  using: "composite"
  steps:
    - name: set variables for dev
      if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
      shell: bash
      run: |
            echo "environment=dev" >>$GITHUB_ENV
            echo "IDENTIFIER=dev" >>$GITHUB_ENV
            echo "ECSPRESSO_ENV=dev" >>$GITHUB_ENV
            echo "DD_VERSION=${{ github.sha }}" >>$GITHUB_ENV
            echo "NOTIFY_SLACK_CHANNEL=#dev_pd_biz_develop" >>$GITHUB_ENV
            echo "SLACK_WEBHOOK=https://hooks.slack.com/services/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" >>$GITHUB_ENV


    - name: set variables for prod
      if: github.event_name == 'release'
      shell: bash
      run: |
            echo "environment=prod" >>$GITHUB_ENV
            echo "IDENTIFIER=prod" >>$GITHUB_ENV
            echo "ECSPRESSO_ENV=prod" >>$GITHUB_ENV
            echo "DD_VERSION=${{ github.event.release.tag_name }}" >>$GITHUB_ENV
            echo "NOTIFY_SLACK_CHANNEL=#dev_pd_biz_production" >>$GITHUB_ENV
            echo "SLACK_WEBHOOK=https://hooks.slack.com/services/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" >>$GITHUB_ENV
