name: PD Biz Deployment

on:
  push:
    branches:

  release:
    types: [published]
  # pull_request:
  #   types: [labeled, synchronize]

concurrency: cd-${{ github.ref_name }}

env:
  AWS_ASSUME_ROLE: arn:aws:iam::961921042948:role/ecs-pd-biz-cicd-role
  AWS_REGION: ap-northeast-1

jobs:
  check_release_tag_and_branch:
    name: check release tag and branch
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      id-token: write
    timeout-minutes: 15
    steps:
      - run: |
          if [[ "${{ github.event_name }}" == "release" ]]; then
            if [[ "${{ github.event.release.target_commitish }}" != "main" ]]; then
              echo "::error:: リリースタグを作成する際は、mainブランチに対して作成してください。"
              exit 1

            elif ! [[ "${{ github.event.release.tag_name }}" =~ ^v.*  ]]; then
              echo "::error:: releaseタグは 'v' から始まるバージョン番号を指定してください。"
              exit 1
            fi
          fi

  build_and_push_image:
    needs: check_release_tag_and_branch
    strategy:
      matrix:
        image-name: [backend]
    name: Build and Push ${{ matrix.image-name }} Image to Amazon ECR Private
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      id-token: write
    timeout-minutes: 15
    steps:
    - name: Replace feature prefix placeholder
      shell: bash
      run: |
        ENV_VARS_FEAT=""NEXT_PUBLIC_BACKEND_API_URL"="https://__feature_prefix__-api.feat.park-direct.jp","NEXT_PUBLIC_SITE_HOSTING_URL"="https://<<feature_prefix>>.feat.onedaypark.jp""
        SUB_DOMAIN="https://__feature_prefix__.feat.onedaypark.jp"

        echo $ENV_VARS_FEAT
        echo $SUB_DOMAIN
        REPLACEMENT="zxxxxxxxx"

        echo "ENV_VARIABLES_FOR_FEAT_BACKEND=${ENV_VARS_FEAT//__feature_prefix__/$REPLACEMENT}" >> $GITHUB_ENV
        echo "SUB_DOMAIN_PREFIX=${SUB_DOMAIN//__feature_prefix__/$REPLACEMENT}" >> $GITHUB_ENV

        echo ${{ env.ENV_VARIABLES_FOR_FEAT_BACKEND }}
        echo ${{ env.SUB_DOMAIN_PREFIX }}
# # Define the initial strings with the placeholder
# ENV_VARS_FEAT="NEXT_PUBLIC_BACKEND_API_URL=https://<<feature_prefix>>-api.feat.park-direct.jp,NEXT_PUBLIC_SITE_HOSTING_URL=https://<<feature_prefix>>.feat.onedaypark.jp"
# SUB_DOMAIN="https://<<feature_prefix>>.feat.onedaypark.jp"

# # The replacement string
# REPLACEMENT="zxxxxxxxx"

# # Use Bash parameter expansion to replace the placeholder and set the GitHub environment variables
# echo "ENV_VARIABLES_FOR_FEAT_BACKEND=${ENV_VARS_FEAT//<<feature_prefix>>/$REPLACEMENT}" >> $GITHUB_ENV
# echo "SUB_DOMAIN_PREFIX=${SUB_DOMAIN//<<feature_prefix>>/$REPLACEMENT}" >> $GITHUB_ENV