name: Pull request closing workflow

on:
  pull_request:

jobs:
  filecreation:
    name: feio
    runs-on: ubuntu-20.04
    steps:
      - name: put
        run: |
         prefix=$(echo we are creature)
         echo "PREFIX=$prefix" >> $GITHUB_ENV
         echo ${{ github.ref }}
         echo ${{ github.head_ref }}
         echo ${{ github.base_ref }}
         echo ${{ github.ref_name }}
         
        echo "BRA=dev" >> $GITHUB_ENV
        echo ${{ env.BRA }}
        echo "BRA=changed" >> $GITHUB_ENV
        echo ${{ env.BRA }}