name: PD Biz Deployment

on:
  push:
    branches:
      - develop
  release:
    types: [published]
  # pull_request:
  #   types: [labeled, synchronize]

concurrency: cd-${{ github.ref_name }}

env:
  AWS_ASSUME_ROLE: arn:aws:iam::961921042948:role/ecs-pd-biz-cicd-role
  AWS_REGION: ap-northeast-1

jobs:
  build_and_push_image:
    strategy:
      matrix:
        image-name: [backend, nginx, fluent-bit]
    name: Build and Push ${{ matrix.image-name }} Image to Amazon ECR Private
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      id-token: write
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # 3.5.2

      - uses: ./.github/actions/set-env-variables
