name: Pull request closing workflow

on:
  pull_request:

jobs:
  filecreation:
    name: feio
    runs-on: ubuntu-20.04
    steps:
      - name: put
        run: |
         prefix=$(echo we are creature)
         echo "PREFIX=$prefix" >> $GITHUB_ENV

      -name: test
        run: echo ${{ env.PREFIX }}


      -name: again
        run: |
          echo aaaaa > text.txt

      -name: last
        run: cat text.txt



